### ISSUE TITLE
Rename GoUldI to MathMLben

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/MathMLben#59]
I liked GoUldI as an internal name. However, I guess the correspondence of the discoveries of [John Gould](https://en.wikipedia.org/wiki/John_Gould) and the discovery of a new quality in Mathematical Markup is not obvious to everybody. Therefore I propose to rename GoUldI to MathMLben.

Moreover, I propose to create a project overview page in #58.

In case of a renaming we need to change:
- [x] the [package name ](https://github.com/ag-gipp/GoUldI/blob/master/package.json#L2)
- [x]  the name of the wmflabs instance in horizon
- [x]  the name of this github repository
- [x]  links in the code to this repository
- [ ]  (optional) rename files, string constants and variable in the source code.

**Comment by AndreG-P** [comment]
I thought the MathMLben will be a simplified web version without the ability to edit the gold standard, just for inspections. No content latex, source latex, identifier and constraints. Just MML and the vmext preview?
If so, I vote for keeping GoUldI alive for further improvements, bug fixes and so on in the future and a second "cleaned" instance called MathMLben.
