### ISSUE TITLE
Decide to use node.js version 8 LTS

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/MathMLben#64]
I think we should only support node version 8 this will also be supported by WMF [soon](https://lists.wikimedia.org/pipermail/services/2018-February/000163.html):
- [x] update node on DRMF -beta
- [x] adjust the Travis configuration

Objections?

**Comment by AndreG-P** [comment]
@physikerwelt 
Node 8 LTS is installed in `/home/andreg-p/.nvm/versions/node/v8.10.0/bin/node`. The global version is installed in `/usr/bin/nodejs` (v7.7.3). This file is always busy and therefore cannot be replaced. Stopping node processes will restarted immediately... Stopping the only two services (apache2 for gouldi and mathpipeline for vmext) doesn't help. Still cannot change or delete old node version.

**Comment by AndreG-P** [comment]
Done. vmext and mathoid are not running on node 8 (they are running on node 7). However, the default of drmf-beta is node 8 and mathmlben is running. https://github.com/ag-gipp/vmext/issues/37

**Comment by physikerwelt** [comment]
@AndreG-P note that mathoid can run on node 8... at least it uses node 8 on travis
